name: Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true

      - name: Set up Python
        run: uv python install

      - name: Set up Virtual Environment
        run: uv venv

      - name: Install dependencies
        run: uv pip install -r pyproject.toml

      - name: Run tests
        run: uv run pytest
